version: '3.7'

services:
  strapi:
    container_name: quest-app-backend
    image: strapi/strapi:3.6.8-node14-alpine
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./backend-quest:/srv/app
    ports:
      - 1337:1337
    depends_on:
      - postgres

  postgres:
    container_name: quest-app-db
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - db:/var/lib/postgresql/data

  react:
    container_name: quest-app-frontend
    build:
      context: ./frontend-quest
      dockerfile: Dockerfile
    volumes:
      - ./frontend-quest:/frontend
    ports:
      - 3000:3000
    depends_on:
      - strapi

volumes:
    db: