version: '3.7'

services:
  strapi:
    container_name: quest-app-backend
    image: strapi/strapi:3.6.8-node14-alpine
    environment:
      DATABASE_CLIENT: 
      DATABASE_NAME: 
      DATABASE_HOST: 
      DATABASE_PORT: 
      DATABASE_USERNAME: 
      DATABASE_PASSWORD: 
    volumes:
      - ./backend-quest:/srv/app
    ports:
      - 1337:1337

  react:
    container_name: quest-app-frontend
    build:
      context: ./frontend-quest
      dockerfile: Dockerfile
    volumes:
      - ./frontend-quest:/frontend
    ports:
      - 3000:3000
    links:
      - "strapi:strapi"
    depends_on:
      - strapi
